server:
  port: 8888
spring:
  datasource:
    name: demo
    url: jdbc:mysql://${DATABASE_IP:10.157.163.47}:${DATABASE_IP_PORT:3306}/${DATABASE_NAME:test}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:hd123}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: ${DATABASE_FILTERS:stat,log4j}
    initialSize: ${DATABASE_INITIALSIZE:10}
    minIdle: ${DATABASE_MINIDLE:10}
    maxActive: ${DATABASE_MAXACTIVE:1000}
    maxWait: ${DATABASE_MAXWAIT:-1}
    timeBetweenEvictionRunsMillis: ${DATABASE_TIMEBETWEENEVICTIONRUNSMILLIS:60000}
    minEvictableIdleTimeMillis: ${DATABASE_MINEVICTABLEIDLETIMEMILLIS:1800000}
    logSlowSql: ${DATABASE_LOGSLOWSQL:true}
    poolPreparedStatements: ${DATABASE_POOLPREPAREDSTATEMENTS:true}
    druid:
      username: ${DATABASE_DRUID_USERNAME:admin}
      password: ${DATABASE_DRUID_PASSWORD:hd123}

#mybatis
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.example.demo.core.entity

#pagehelper\u5206\u9875\u63D2\u4EF6
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# \u914D\u7F6E\u65E5\u5FD7\u7EA7\u522B\uFF0C\u8BA9hibernate\u6253\u5370\u51FA\u6267\u884C\u7684SQL
logging:
  config: classpath:logback.xml
  level:
    root: INFO
    com.qianfan123.sail.inf.client: DEBUG
  feignClient:
    #\u65E5\u5FD7\u7EA7\u522B\uFF1ANONE, BASIC, HEADERS, FULL
    level: ${LOGGING_FEIGNCLIENT_LEVEL:BASIC}

#\u7EBF\u4E0A\u6539\u4E3Afalse \uFF0C\u5C06\u4E0D\u5C55\u793Aswagger\u63A5\u53E3\u5177\u4F53\u4FE1\u606F
swagger:
      show: true